/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SudokuSolver */

#ifndef _Included_SudokuSolver
#define _Included_SudokuSolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SudokuSolver
 * Method:    SudokuSolve
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SudokuSolver_SudokuSolve
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
