/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SalesMan */

#ifndef _Included_SalesMan
#define _Included_SalesMan
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SalesMan
 * Method:    my_dijkstras
 * Signature: ([[IIII)I
 */
JNIEXPORT jint JNICALL Java_SalesMan_my_1dijkstras
  (JNIEnv *, jobject, jobjectArray, jint, jint, jint);

/*
 * Class:     SalesMan
 * Method:    display
 * Signature: ([[I)V
 */
JNIEXPORT void JNICALL Java_SalesMan_display
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
